version: "3.8"
services:
  postgresql-db:
    image: postgres
    restart: always
    container_name: postgresql-db-data
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: diego12345
      POSTGRES_USER: postgres
      POSTGRES_DB: sulab
    ports:
      - "5432:5432"

    app:
    container_name: sulab-v1
    image: diegoacunaj/sulab-v1
    restart: always
    ports:
      - "8091:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-db:5432/sulab
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=diego12345
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgresql-db

  frontend:
    container_name: sulab-v1
    image: diegoacunaj/sulab-v1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - a_default  # Conectarse a la red definida "a_default"

networks:
  a_default:
